### ISSUE TITLE
flextools_run_module: unprotected mutating script returns opaque "'str' object has no attribute 'get'" instead of the unprotected_mutations_detected guidance

### ISSUE THREAD

**Issue by MattGyverLee** [MattGyverLee/FlexToolsMCP#82]
## Summary

Submitting any **unprotected mutating** script to `flextools_run_module` returns a bare, unactionable error:

```
'str' object has no attribute 'get'
```

…instead of the `unprotected_mutations_detected` guidance the preflight actually computed. The gate itself works correctly — it detects the mutation and decides to reject — but the handler crashes while *logging* that rejection, so the guidance never reaches the caller.

Net effect: the one message that tells you how to fix your script (`wrap writes in if modifyAllowed:`) is replaced by an error that points nowhere. As an agent I could not tell whether I had a bad script, a bad project, a permissions problem, or a server fault, and I burned a fair number of round trips bisecting it.

Reproduced on **current `main` (`994793e`, 2.9.0)**. Introduced in **`a449605`** (2026-05-30, *"fix: Log writeability rejects with per-issue DEBUG, matching casting"*).

## Root cause

`execution.py:2657-2661` iterates `cert["raw_lcm_patterns"]` treating each element as a dict:

```python
for p in raw_lcm[:10]:
    op_logger.debug(
        f"  writeability: line={p.get('line')} method={p.get('method')} "
        f"context={(p.get('context') or '')[:80]!r}"
    )
```

But `raw_lcm_patterns` is a list of **plain strings**. It comes from `detect_cud_operations()["operations"]`, which appends formatted labels:

- `validators.py:260` — `operations.append(f"CREATE ({label})")`
- `validators.py:2478` — `raw_lcm_patterns.extend(cud_info["operations"])`

So `p.get(...)` raises `AttributeError` on the first element.

This looks like a copy-paste from the immediately preceding loop over `unprotected_lcm` (`execution.py:2652-2656`), which uses the *identical* field names `line` / `method` / `context` — and there those fields are correct, because `unprotected_liblcm_calls` genuinely holds `{"method", "line", "context"}` dicts. The `raw_lcm` list simply doesn't have that shape.

Worth noting the newer `build_writeability_payload()` (`validators.py:2640-2659`) *does* build proper dicts with `{"line", "call", "kind": "raw_lcm"}`. The buggy loop reads as though it were written against that structure but wired to `cert["raw_lcm_patterns"]` instead.

## Minimal reproduction

```python
from flexicon import LexEntryOperations
ops = LexEntryOperations(project)
e = ops.Create("zzz", create_blank_sense=True)
report.Info("created entry: %s" % e.Guid)
```

```
flextools_run_module(code=<above>, project_name="<any>", write_enabled=True, confirmed=True)
-> isError: true
-> "'str' object has no attribute 'get'"
```

Same result for every combination of `write_enabled` / `confirmed` — the crash is upstream of both.

### Isolated confirmation (no MCP round trip)

```python
from flextoolsmcp.server.validators import detect_cud_operations, certify_script_readonly

code = ('from flexicon import LexEntryOperations\n'
        'ops = LexEntryOperations(project)\n'
        'e = ops.Create("z", create_blank_sense=True)\n')

print(detect_cud_operations(code)["operations"])   # ['CREATE (Create())']
raw = certify_script_readonly(code, None, None)["raw_lcm_patterns"]
print([type(p).__name__ for p in raw])             # ['str']

for p in raw[:10]:
    p.get("line")        # AttributeError: 'str' object has no attribute 'get'
```

## The tell in the server log

`flextools_get_operation_logs` shows the reject being decided and the *first* two loops completing, then nothing — the crash lands precisely at the third loop:

```
INFO  | Preflight writeability: mutating=1 (flexicon=1 unprotected_lcm=0 raw_lcm=1) (rejected)
DEBUG |   writeability: class=LexEntryOperations method=Create source=index
                                  <-- unprotected_lcm loop: 0 items, nothing logged
                                  <-- raw_lcm loop: 1 item -> AttributeError, no "Preflight reject" line follows
```

## `validate_only: true` is unaffected

The parallel gate-assembly path (`execution.py:1674-1686`) puts the same data in `issues` **without** iterating it as dicts, so it returns correctly:

```json
{
  "gate": "unprotected_writes",
  "passed": false,
  "issues": ["LexEntryOperations.Create()"],
  "guidance": { "error": "unprotected_mutations_detected", ... }
}
```

That asymmetry is a useful workaround (`validate_only: true` surfaces the real guidance) and also localises the bug to the logging loop rather than the gate.

## Suggested fix

The elements are strings, so just log them as strings:

```python
for p in raw_lcm[:10]:
    op_logger.debug(f"  writeability: raw_lcm_pattern={p!r}")
```

Alternatively, make `raw_lcm_patterns` carry `{"line", "method", "context"}` dicts to match the sibling lists — but that changes a structure `validators.py:1945`, `validators.py:1993` and `recipe_validator.py:93` all currently consume as strings, so the string-logging fix is the smaller change.

Either way this loop is diagnostic-only: it must never be able to take down the response it is describing. Wrapping the whole per-issue DEBUG block in a `try/except Exception` would make that structural, so a future shape drift degrades the log rather than the tool result.

## Pattern audit

Swept every `raw_lcm_patterns` / `cud_info["operations"]` consumer in `src/`:

| Site | Treats elements as | Correct? |
|---|---|---|
| `execution.py:2657` | dicts (`p.get(...)`) | **NO — this bug** |
| `execution.py:2645` | `len()` only | yes |
| `validators.py:1945` `detected_operations` | passthrough | yes |
| `validators.py:1993` `operations_that_will_execute` | passthrough | yes |
| `validators.py:2517` | truthiness only | yes |
| `recipe_validator.py:93` | f-string interpolation | yes |

Single-site defect; no siblings to fix.

## Environment

- FlexToolsMCP `main` @ `994793e` (2.9.0), editable install
- Python 3.12, Windows 11
- LibLCM 11.0.0, Flexicon 4.3.0, FlexLibs 1.2.8

### Unrelated launcher note (root cause NOT established -- corrected)

`uvx --from flextools-mcp flextoolsmcp` -- the command `claude mcp add` suggests -- fails at startup on this machine with:

```
ImportError: cannot import name 'run' from 'flextoolsmcp.server'
```

**Correction to my first version of this note.** I originally wrote that the published wheel is broken and does not export `run`. That was wrong and I should not have asserted it. What actually checks out:

- `flextoolsmcp/server.py` **does** ship in the wheel and **does** define `run()` (line 1123).
- `uv run --no-project --with flextools-mcp python -c "from flextoolsmcp.server import run"` imports it fine.
- `uv run --no-project --with flextools-mcp flextoolsmcp` starts the server normally (loads LibLCM 11.0.0 / Flexicon 4.3.0).

So the package and its console script are both fine. Only the `uvx --from` invocation fails, reproducibly, and `uv cache clean flextools-mcp` (799 files, 340 MB) did not change it. **I have not established why**, so please treat this as a symptom report, not a diagnosis.

One thing here I would still call a defect on its own merits: the lazy `__getattr__` shim in `server/__init__.py` **masks the underlying failure**. Whatever goes wrong while it loads `server.py`, the caller only ever sees `cannot import name 'run'` with no chained exception -- which is precisely why I mis-diagnosed this. Re-raising with the cause attached would make this class of problem self-diagnosing:

```python
except Exception as exc:
    raise ImportError(
        f"lazy load of server.py failed while resolving {name!r}"
    ) from exc
```

Related fragility worth a look while you are in there: the shim's `sys.path` insertion is load-bearing. `server.py` carries 5 absolute `from server.X import ...` statements for its script-mode branch, and the shim puts `site-packages/flextoolsmcp` on `sys.path`, which makes `server`, `kernel`, `handlers` importable as *top-level* names. That is the same sibling-shadowing hazard the issue-#10 comment documents at length, and it is where I would look first for the `uvx` difference.

Happy to split this into its own issue -- it is unrelated to the `raw_lcm` crash above and only rode along because I hit both in one session.

### Minor: stale editable-install metadata

`importlib.metadata.version("flextools-mcp")` reports `2.3.3` while the checkout is 2.9.0, so the tool's own `update_notice` claims an update is available when you are already ahead of it. Cosmetic, but it sent me looking in the wrong direction at first.

**Comment by MattGyverLee** [comment]
**Correction to the packaging note at the bottom of this issue** (the main `raw_lcm` report above is unaffected and stands as filed).

I originally wrote that the published PyPI build was broken and that `flextoolsmcp.server` "doesn't export `run`". That was wrong, and I've rewritten the section. Checking it properly:

- `flextoolsmcp/server.py` ships in the wheel and defines `run()` at line 1123.
- `uv run --no-project --with flextools-mcp python -c "from flextoolsmcp.server import run"` -> imports fine.
- `uv run --no-project --with flextools-mcp flextoolsmcp` -> server starts normally (LibLCM 11.0.0, Flexicon 4.3.0).

The package and console script are fine. Only `uvx --from flextools-mcp flextoolsmcp` fails, and `uv cache clean flextools-mcp` didn't change it — so it isn't a stale cache either. I have not established the cause, so it's now written up as a symptom, not a diagnosis.

What misled me is worth keeping as a finding in its own right: the lazy `__getattr__` shim reports every failure as `cannot import name 'run'` with **no chained exception**, so the actual error is invisible. Re-raising `from exc` would have saved me the wrong guess.

Sorry for the noise in the original framing.
